# Generated by Django 3.2.16 on 2023-02-07 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('body', models.TextField()),
                ('lesson_time_image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('free_or_pay', models.CharField(max_length=5)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
