# Generated by Django 3.2.16 on 2023-02-08 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_education_name', models.CharField(max_length=55)),
                ('best_education_body', models.TextField()),
                ('best_education_images1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('best_education_images2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('best_education_images3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('top_managment_name', models.CharField(max_length=55)),
                ('top_managment_body', models.TextField()),
                ('top_managment_images1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('top_managment_images2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('top_managment_images3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('quality_meeting_name', models.CharField(max_length=55)),
                ('quality_meeting_body', models.TextField()),
                ('quality_meeting_images1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('quality_meeting_images2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('quality_meeting_images3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
