# Generated by Django 3.2.16 on 2023-02-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_about_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_acount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.RemoveField(
            model_name='about_user',
            name='best_education_images2',
        ),
        migrations.RemoveField(
            model_name='about_user',
            name='best_education_images3',
        ),
        migrations.RemoveField(
            model_name='about_user',
            name='quality_meeting_images1',
        ),
        migrations.RemoveField(
            model_name='about_user',
            name='quality_meeting_images2',
        ),
        migrations.RemoveField(
            model_name='about_user',
            name='top_managment_images1',
        ),
        migrations.RemoveField(
            model_name='about_user',
            name='top_managment_images3',
        ),
    ]
