# Generated by Django 3.2.16 on 2023-02-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20230215_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Cotegories'},
        ),
        migrations.AlterField(
            model_name='videos_post',
            name='body',
            field=models.TextField(),
        ),
    ]
